### ISSUE TITLE
Support for placing additional components with each switch such as RGB LEDs?

### ISSUE THREAD

**Issue by Bob837217** [zykrah/kicad-kle-placer#7]
Do you have plans to support RGB LEDs in addition to the existing Diode placement option?  I would like to build a board with per key RGB LEDs in addition to Diodes.

This is a fantastic tool by the way.  Noah Kiser put me onto this tool in his excellent 2 part keyboard PCB KiCAD series (part 1): https://www.youtube.com/watch?v=6Z49bynRqj8

**Comment by zykrah** [comment]
Hi, I may explore adding this feature in the future as something dedicated.

In the meantime, you can try adamws' kicad placer, which has support for adding any number of extra components to place with respect to switches.

OR

More easily, you can just run the plugin once normally, then change the diode reference designator to `LED` instead of `D` (or whatever designator you'll use for your LEDs)

**Comment by Bob837217** [comment]
Yes, I subsequently messaged adamws too and he says the functionality is there on v0.5 of his project. Thanks for the reply, will close this out.  Thanks also for your work on this one.
